#!/bin/bash

#feh --bg-scale /home/iraklis/Pictures/portal-left.jpg --bg-scale /home/iraklis/Pictures/portal-right.jpg &
#feh --bg-scale /home/iraklis/Pictures/wallpapers/0016.jpg --bg-scale /home/iraklis/Pictures/wallpapers/0016.jpg &
source ~/.config/feh/set_background.sh
picom &
xrdb -load .Xresources
dropbox start & 
trayer --edge top --align right --SetDockType true --SetPartialStrut true --expand true --width 5 --transparent false --tint 0x000000 --height 17 --alpha 10 &
xscreensaver -no-splash &
#xrandr --output DP-1 --primary --left-of DVI-D-1
#xrandr --output HDMI-1 --rotate right
exec xmonad

